---
# SecretStore defines how to connect to GCP Secret Manager
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-secret-store
  namespace: zenml
spec:
  provider:
    gcpsm:
      projectID: zenml-472221  # Updated to correct project ID
      # Use Workload Identity - the same service account ZenML uses
      auth:
        workloadIdentity:
          clusterLocation: australia-southeast1
          clusterName: zenml
          serviceAccountRef:
            name: zenml-service-account  # Updated to correct service account name
