---
# SecretStore defines how to connect to GCP Secret Manager
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-store
  namespace: zenml
spec:
  provider:
    gcpsm:
      # Use Workload Identity - the same service account ZenML uses
      auth:
        workloadIdentity:
          clusterLocation: australia-southeast1
          clusterName: zenml
          serviceAccountRef:
            name: zenml-server  # This matches your ZenML service account
      projectId: zenml-470505
---
# ExternalSecret defines what secrets to fetch and how to transform them
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zenml-secrets
  namespace: zenml
spec:
  refreshInterval: 150s  # Refresh every 2.5 minutes
  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore
  target:
    name: zenml-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        # Database configuration
        database-url: "{{ .database_url }}"
        database-password: "{{ .database_password }}"
        
        # ZenML server configuration
        default-username: "{{ .default_username }}"
        default-password: "{{ .default_password }}"

  data:
    # Map GCP Secret Manager secret names to template variables
    - secretKey: database_url
      remoteRef:
        key: zenml-database-url
    
    - secretKey: database_password
      remoteRef:
        key: zenml-database-password
    
    - secretKey: default_username
      remoteRef:
        key: zenml-default-username
    
    - secretKey: default_password
      remoteRef:
        key: zenml-default-password
        
