apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/refresh: normal
    argocd.argoproj.io/sync-wave: "1"  # Deploy before cluster-issuers (wave 2)
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.18.2
    helm:
      releaseName: cert-manager
      parameters:
        - name: installCRDs
          value: "true"
        - name: global.leaderElection.namespace
          value: cert-manager
      values: |
        # Additional cert-manager configuration
        installCRDs: true
        global:
          leaderElection:
            namespace: cert-manager
        # Enable prometheus metrics
        prometheus:
          enabled: true
          servicemonitor:
            enabled: false
        # Webhook configuration
        webhook:
          timeoutSeconds: 10
        # Resource limits for production
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi
        cainjector:
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
        webhook:
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true  # Important for CRDs
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  # Health check configuration
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
