apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"  # Deploy after infrastructure (wave 2)
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # Helm chart source - Using Bitnami MLflow chart
    - repoURL: https://charts.bitnami.com/bitnami
      chart: mlflow
      targetRevision: 4.0.4
      helm:
        valueFiles:
          - $values/src/mlflow/values.yaml
    # Values source from our repository
    - repoURL: https://github.com/Philippe-Neveux/zenml-mlops-stack.git
      targetRevision: HEAD
      ref: values
  
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  revisionHistoryLimit: 3
  
