apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zenml-cert-cleanup
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Philippe-Neveux/zenml-mlops-stack.git
    targetRevision: HEAD
    path: src/k8s-cluster/cert-cleanup
  destination:
    server: https://kubernetes.default.svc
    namespace: zenml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
