# Minimal MLflow values for schema compliance
replicaCount: 1

image:
  repository: burakince/mlflow
  tag: "2.22.2"
  pullPolicy: IfNotPresent

serviceAccount:
  create: false
  name: mlflow

backendStore:
  databaseMigration: true
  databaseConnectionCheck: true
  mysql:
    enabled: true
    host: "10.175.0.3"
    port: 3306
    database: "mlflow"
    user: "mlflow_user"
    password: ""
    driver: "pymysql"
  existingDatabaseSecret:
    name: "mlflow-database-secret"
    usernameKey: "username"
    passwordKey: "password"

postgresql:
  enabled: false

mysql:
  enabled: false

artifactRoot:
  proxiedArtifactStorage: false
  gcs:
    enabled: true
    bucket: "zenml-mlflow-artifacts"
    path: ""

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
  hosts:
    - host: mlflow.34.40.173.65.nip.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: mlflow-tls
      hosts:
        - mlflow.34.40.173.65.nip.io

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 200m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
