# ZenML Custom Values - Git Safe Version
# Sensitive values are fetched from GCP Secret Manager via External Secrets Operator

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# ZenML server related options.
zenml:
  replicaCount: 1
  
  # Image configuration
  image:
    repository: zenml/zenml-server
    pullPolicy: IfNotPresent
    tag: "0.84.3"
  
  # Use secrets from External Secrets Operator
  # Database configuration - values come from zenml-secrets secret
  database:
    url:
      secretName: zenml-secrets
      secretKey: database-url
    password:
      secretName: zenml-secrets
      secretKey: database-password
    
  # Default user configuration - values come from zenml-secrets secret  
  defaultUsername:
    secretName: zenml-secrets
    secretKey: default-username
  defaultPassword:
    secretName: zenml-secrets
    secretKey: default-password
  
  # Ingress configuration
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - host: zenml.34.40.173.65.nip.io
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: zenml-tls
        hosts:
          - zenml.34.40.173.65.nip.io

  # Secrets store configuration
  secretsStore:
    enabled: true
    type: gcp
    gcp:
      authMethod: implicit  # Use Workload Identity
      authConfig:
        project_id: zenml-470505

# Service Account configuration (Workload Identity)
serviceAccount:
  create: true
  annotations:
    iam.gke.io/gcp-service-account: zenml-zenml@zenml-470505.iam.gserviceaccount.com
  name: "zenml-server"

# Pod configuration
podAnnotations: {}
podSecurityContext: {}

securityContext:
  runAsNonRoot: true
  runAsUser: 1000

# Resource configuration
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

# Node selection
nodeSelector: {}
tolerations: []
affinity: {}

# Autoscaling
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
