name: Deploy MkDocs

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'pyproject.toml'
      - '.github/workflows/docs.yml'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Install uv
        uses: astral-sh/setup-uv@v5
          
      - name: Install dependencies
        run: |
          uv sync --group doc
          
      - name: Deploy to GitHub Pages
        run: |
          uv run mkdocs gh-deploy --force